### ISSUE TITLE
Touchpad movements jerky

### ISSUE THREAD

**Issue by shubham1172** [shubham1172/remote-play#1]
All events from hammer.js are sent directly as REST API calls to the server to pyautogui. There are jitters and jerks in the mouse cursor movement. Help needed on ways to smoothen the experience for the end user.

**Comment by wahwic** [comment]
Can I have a go at solving this issue?

**Comment by shubham1172** [comment]
Sure @wahwic, feel free to take a stab at it. How are you planning to do it? Web sockets might be one viable option.

**Comment by wahwic** [comment]
The easiest kind-of-a-solution would be changing 
`def handle_touchpad(action, dx: int = 0, dy: int = 0):`
to
`def handle_touchpad(action, dx: float = 0, dy: float = 0):`

but I am trying out fastapi.websockets if it gives a better experience

**Comment by shubham1172** [comment]
Yup, it will still overload the server with a lot of REST API calls. Web sockets might be a better option here. 

I will assign you this issue! ATB.
