### ISSUE TITLE
Add right mouse button click support

### ISSUE THREAD

**Issue by shubham1172** [shubham1172/remote-play#27]
Double tap to click RMB should be added.

**Comment by harshlancer** [comment]
I want to work on this issue can you tell me more about it.

**Comment by shubham1172** [comment]
@harshlancer sure! If you use remote-play, it currently supports two actions with the touchpad - moving the cursor, and left mouse button click (single tap). With this issue, we want to add support for right mouse button click. It will involve
1. Adding a hammer event listener for double tap that emits a web-socket message in [index.js](https://github.com/shubham1172/remote-play/blob/main/static/index.js)
2. Updating the text in touchpad area to indicate double-tap as a supported gesture, in [index.html](https://github.com/shubham1172/remote-play/blob/main/static/index.html)
3. Translating the new web-socket message to right mouse button click using PyAutoGui in [main.py](https://github.com/shubham1172/remote-play/blob/main/main.py)
4. And finally, updating the Readme to reflect the same in [README.md](https://github.com/shubham1172/remote-play/blob/main/README.md)

Let me know if you want to take this up, I will assign the issue to you.

**Comment by harshlancer** [comment]
@shubham1172  I can do it but I'll need tons of guidance as I've no experience in this field.
I know how to code on JS.
If you'll allow me I can start working.

**Comment by shubham1172** [comment]
Sure @harshlancer! You can start with the code-pointers I shared above to extend the functionality. It will be similar to how left mouse button click is implemented. I have assigned this issue to you.

**Comment by harshlancer** [comment]
Ok thankyou very much I'll report to you shortly.

**Comment by tesla-srt** [comment]
I've had a look at the documentation you provided. I'd like to take a crack at it too, if possible :)

**Comment by shubham1172** [comment]
@tesla-srt, let me know if you want to take it up, this issue is up-for-grabs again.

**Comment by tesla-srt** [comment]
Alright, let's do it! I'll clone the codebase this evening and take a wack at it :)
Are there any specific tests that are being used that I can run?

**Comment by shubham1172** [comment]
@tesla-srt, we don't have any test cases as of today, but you can do manual testing to ensure (1) new feature works and (2) old features are not broken.

**Comment by shubham1172** [comment]
@Emeka-Ugbanu-hub I have assigned this to @tesla-srt based on a first-come basis. Thanks for showing interest in helping, you can try to pickup other issues in this repo as well.

**Comment by Emeka-Ugbanu-hub** [comment]
Ok Thanks

**Comment by tesla-srt** [comment]
Thanks for the patience - celebratory weekend in my household - Just touched up the changes you mentioned the latest commit  👍
