### ISSUE TITLE
Beautify touchpad

### ISSUE THREAD

**Issue by shubham1172** [shubham1172/remote-play#3]
Touchpad UI looks out of place. It should be similar to the other UI components.

**Comment by jjcrab** [comment]
Hi can you elaborate more on the requirement and expectation?

**Comment by shubham1172** [comment]
Basic requirement: 
- Inform the user about the supported actions: preferably as some background text like in the image below (Keep It Simple)
- Design should match with other UI components: all the buttons are white, and the touchpad is black (with a gray background text)

Something like this (excuse the quick prototyping).

![image](https://user-images.githubusercontent.com/22132944/114295980-5a0dfb80-9ac6-11eb-84e8-26c1e2f8942a.png)

Feel free to propose new ideas for the same.
