### ISSUE TITLE
Add support for two-finger scrolling

### ISSUE THREAD

**Issue by shubham1172** [shubham1172/remote-play#30]
Two finger to scroll support. Will be useful for browsing, in addition to media controls.

**Comment by JasonT1085** [comment]
Hi! I would like to take up this issue, would you tell me more about this? Thank you!

**Comment by shubham1172** [comment]
Thank you @JasonT1085 for showing interest! This will be a similar work item as #27 for adding scroll capabilities to the touchpad, using hammer.js and web sockets. PR for #27 will be merged as soon as the last few bits are done, but you can read that to get an idea of how to build on top. Let me know if you have any concerns.

**Comment by JasonT1085** [comment]
Awesome! Thank you for having me!

**Comment by tesla-srt** [comment]
Hiya, I like what's going on here :)
I thought I might add my suggestion, let me know your thoughts.
What if instead of using pinch for scrolling there was the addition of a secondary and tertiary text-area nested near the mouse control.
This way it is more conducive to single hand use.

**Comment by JasonT1085** [comment]
Oh like another area specific for scrolling? Perhaps an area near the right edge for thumb scrolling? And if preferred, switch the scroll area to the left side for left-handed users?

**Comment by shubham1172** [comment]
Love the ideas here, and the accessibility part for left-handed users. This is very similar to [How do I use Virtual Scrolling? -  Synaptics TouchPad Documentation](https://documentation.help/Synaptics-TouchPad/synt2zc7.htm).

Since some websites also might have a better experience with horizontal scrolling, it can be added too. For example - Amazon Prime:
![image](https://user-images.githubusercontent.com/22132944/155872858-06737abe-6023-4760-8545-72efd16d2b76.png)

For the accessibility part, it can be built-in and configurable using #32
