### ISSUE TITLE
Conditionally support features based on OS

### ISSUE THREAD

**Issue by shubham1172** [shubham1172/remote-play#38]
Features like horizontal scrolling is only available on select platforms. There might be similar features in the future too. 

As of today, all features are present on the UI even though it's unsupported. This issue is to selectively support features. Some features can be behind a feature flag that's conditionally rendered based on the operating system. This can also allow flighting in future when we release preview features behind configurations.

**Comment by harshlancer** [comment]
Can you provide a little more context?

**Comment by harshlancer** [comment]
Which features are needed to run and when?

**Comment by shubham1172** [comment]
For now, it's only horizontal scrolling - it is not supported on Windows. The idea is that the UI can ask the server which experimental features are supported (based on the computer remote-play is running on), and conditionally render that feature in UI. Something like:

Request: `GET /metadata`
Response: 
```json
{
    "OS": "Windows"
    "experimental-features": {
        "hscroll": false
     }
}
```

Experimental features can contain features that only work on a particular OS, or features that are truly experimental (beta mode, not fit for production - although this is a very far off thing and not really needed now).

Based on this, the UI can conditionally render.

**Comment by shivamshrey** [comment]
Hi @shubham1172, does this require JavaScript know-how?

**Comment by shubham1172** [comment]
> Hi @shubham1172, does this require JavaScript know-how?

If I get your question correctly, I don't think you need to know a lot about JavaScript to contribute to this. The Python server needs to return the correct JSON, and the JavaScript client has to selectively render items based on that.

**Comment by andrewasche** [comment]
I think I have something that can work

**Comment by andrewasche** [comment]
I can figure out how to create a branch

**Comment by andrewasche** [comment]
I *can't figure out how to create a branch

**Comment by andrewasche** [comment]
This is the pull request I created for this issue, because I had issues with branches I forked

https://github.com/shubham1172/remote-play/pull/46

**Comment by shubham1172** [comment]
> I *can't figure out how to create a branch

Maybe this can help https://www.atlassian.com/git/tutorials/using-branches

For now it's ok even if your PR is from your main branch, I will review it, thanks!

**Comment by danilobatson** [comment]
@shubham1172 is this issue still open?

**Comment by shubham1172** [comment]
@danilobatson yes, #46 addresses the server-side part but we still need a client-side handling to render things selectively based on the `/metadata` response.
