### ISSUE TITLE
Add CLI flags for all environment variables

### ISSUE THREAD

**Issue by shubham1172** [shubham1172/remote-play#40]
There should be a CLI flag for each environment variable.
Precedence should be 
1. CLI flag
2. Environment variable

|Environment variable|CLI flag|Exists|
|--|--|--|
|`REMOTE_PLAY_SSL_CERT`|`--ssl-cert`|✅|
|`REMOTE_PLAY_SSL_KEY`|`--ssl-key`|✅|
|`REMOTE_PLAY_PORT`|`--port`|❌|
|`REMOTE_PLAY_HOST`|`--host`|❌|

**Comment by zt4ff** [comment]
Hi @shubham1172 

Can I figure this out and make a PR?
This will be my first time contributing code to open source

**Comment by zt4ff** [comment]
I made a PR here: https://github.com/shubham1172/remote-play/pulls
