### ISSUE TITLE
Dark theme for Remote play

### ISSUE THREAD

**Issue by shubham1172** [shubham1172/remote-play#9]
- [x] Detect user's system preference
- [x] Implement a toggle to the right of the Header
- [x] Save user's preference in local storage

**Comment by shubham1172** [comment]
Awesome, you can also start with #3 as that might help us solve #9 in a more elegant way. There is a PR by @jjcrab but it has some finishing touches left.

**Comment by dbarrous** [comment]
I'll get a PR out for this one next week :)

**Comment by shubham1172** [comment]
Thank you for your help 😀 At the moment, I don't have any other Open Source project with any active development going on. Feel free to browse from the old ones and we can pick up something from there!

**Comment by williamye51** [comment]
@shubham1172 Hello, I was wondering if I can work on just implementing a toggle to the right of the header.

**Comment by shubham1172** [comment]
@williamye51 sure, thanks for your help! If you are interested, we can also try to implement the rest of the PR together. I can help around it if needed.

**Comment by williamye51** [comment]
@shubham1172 I ended up having time to implement the rest and just made a PR! Thanks!
